SELECT *
FROM EMPLOYEES 
WHERE SALARY = (
    SELECT max(SALARY)
    FROM EMPLOYEES  
);
select *
from jobs 
where job_id = 'AD_PRES';
/*min
max
sum
count
avg*/

---Mostrar el salario total por departamento:
SELECT N.DEPARTMENT_NAME, SUM(A.SALARY) as TOTAL_SALARY
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS N
ON (A.DEPARTMENT_ID = N.DEPARTMENT_ID)
GROUP BY N.DEPARTMENT_NAME
ORDER BY N.DEPARTMENT_NAME;

--CANTIDAD DE EMPLEADOS POR DEPARTAMENTO
SELECT N.DEPARTMENT_NAME, COUNT(1) as TOTAL_EMPLOYEES
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS N
ON (A.DEPARTMENT_ID = N.DEPARTMENT_ID)
GROUP BY N.DEPARTMENT_NAME
ORDER BY N.DEPARTMENT_NAME;


--CANTIDAD DE EMPLEADOS POR PAIS UTILIZANDO PRODUCTOS CARTESIANOS Y (+)
SELECT D.COUNTRY_NAME, COUNT(1) AS EMPLOYEES_COUNT
FROM EMPLOYEES A,
    DEPARTMENTS B,
    LOCATIONS C,
    COUNTRIES D
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID(+)
AND     B.LOCATION_ID = C.LOCATION_ID(+)
AND     C.COUNTRY_ID = D.COUNTRY_ID(+)
GROUP BY D.COUNTRY_NAME
ORDER BY D.COUNTRY_NAME;


--MOSTRAR LOS PAISES QUE TENGAN MAS DE 5 EMPLEADOS UTILIZANDO PRODUCTOS CARTESIANOS Y (+)
SELECT  upper(D.COUNTRY_NAME) as COUNTRY_NAME,
        COUNT(1) AS EMPLOYEES_COUNT
FROM EMPLOYEES A,
    DEPARTMENTS B,
    LOCATIONS C,
    COUNTRIES D
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID(+)
AND     B.LOCATION_ID = C.LOCATION_ID(+)
AND     C.COUNTRY_ID = D.COUNTRY_ID(+)
--AND COUNTRY_NAME = 'United Kingdom'
GROUP BY upper(D.COUNTRY_NAME) 
HAVING COUNT(1) >5
ORDER BY upper(D.COUNTRY_NAME);



select to_char(hire_date, 'MM-YYYY'), count(1)
from employees
group by to_char(hire_date, 'MM-YYYY')
order by 1;



