SELECT  INITCAP(B.NOMBRE || ' ' || B.APELLIDO) AS NOMBRE_COMPLETO,
        C.NOMBRE_CAMPUS,
        D.NOMBRE_LUGAR AS LUGAR_NACIMIENTO,
        E.NOMBRE_LUGAR AS LUGAR_RESIDENCIA
  FROM TBL_ALUMNOS A,
      TBL_PERSONAS B,
      TBL_CAMPUS C,
      TBL_LUGARES D,
      TBL_LUGARES E

WHERE A.CODIGO_ALUMNO = B.CODIGO_PERSONA
AND B.CODIGO_CAMPUS = C.CODIGO_CAMPUS
AND B.CODIGO_LUGAR_NACIMIENTO = D.CODIGO_LUGAR
AND B.CODIGO_LUGAR_RESIDENCIA = E.CODIGO_LUGAR;


SELECT CODIGO_ALUMNO,
      CANTIDAD_ASIGNATURAS,
      COUNT(*) CANTIDAD_CARRERAS,
      SUM(CANTIDAD_CLASES_APROBADAS) ASIGNATURAS_APROBADAS
  FROM TBL_CARRERAS_X_ALUMNOS A,
        TBL_CARRERAS B
    WHERE A.CODIGO_CARRERA = B.CODIGO_CARRERA
GROUP BY CODIGO_ALUMNO, CANTIDAD_ASIGNATURAS;

SELECT CODIGO_ALUMNO, SUM(CANTIDAD_CLASES_APROBADAS)
  FROM TBL_CARRERAS_X_ALUMNOS
GROUP BY CODIGO_ALUMNO;


SELECT A.CODIGO_ALUMNO, SUM(A.CANTIDAD_CLASES_APROBADAS), SUM(B.CANTIDAD_ASIGNATURAS),
        ROUND(SUM(A.CANTIDAD_CLASES_APROBADAS)/SUM(B.CANTIDAD_ASIGNATURAS),3) *100
  FROM TBL_CARRERAS_X_ALUMNOS A,
      TBL_CARRERAS B
WHERE A.CODIGO_CARRERA = B.CODIGO_CARRERA
GROUP BY CODIGO_ALUMNO;


SELECT *
  FROM TBL_CARRERAS;

SELECT *
  FROM TBL_ALUMNOS;





