
  CREATE TABLE "HR"."MANAGERS" 
   (	"EMPLOYEE_ID" NUMBER(6,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(25 BYTE), 
	"EMAIL" VARCHAR2(25 BYTE)
);

SELECT * 
FROM MANAGERS;

INSERT INTO MANAGERS(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL;


SELECT X
FROM Y
WHERE Z;


SELECT *
FROM EMPLOYEES
WHERE SALARY = 
    (
        SELECT MIN(SALARY)
        FROM EMPLOYEES
    );
    
    
    
    
SELECT  FIRST_NAME, SALARY,
        ROUND(SALARY/(
            SELECT SUM(SALARY)
            FROM EMPLOYEES
        )*100,2)||'%' PORCENTAJE
FROM EMPLOYEES;


SELECT SUM(PORCENTAJE) COMPROBACION
FROM (
    SELECT  FIRST_NAME, SALARY,
            SALARY/(
                SELECT SUM(SALARY)
                FROM EMPLOYEES
            )*100 PORCENTAJE
    FROM EMPLOYEES
);


SELECT SUM(SALARY)
FROM EMPLOYEES;


---Subconsultas utilizando with
WITH SALARIO_TOTAL AS (
    SELECT SUM(SALARY) TOTAL
    FROM EMPLOYEES
)
SELECT  FIRST_NAME, SALARY,
        ROUND(SALARY/(SALARIO_TOTAL.TOTAL)*100,2)||'%' PORCENTAJE
FROM EMPLOYEES;

WITH SALARIO_TOTAL AS (
    SELECT SUM(SALARY) TOTAL
    FROM EMPLOYEES
)
SELECT *
FROM SALARIO_TOTAL;


